package:
    name: pyg-bond
    version: 0.0.11

source:
    path: ../src
	
build:
    include_recipe: False
    number: 0
    noarch: python

requirements:
    build:
        - numpy             >=1.18.1
        - pandas            >=0.23.0
        - pyg-base          >=0.0.19
    run:
        - numpy             >=1.18.1
        - pandas            >=0.23.0
        - pyg-base          >=0.0.19
about:
    home: https://github.com/gityoav/pyg-bond
    license: GNU